create table public.sponsored_accounts (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  account_pubkey text null,
  sponsor_pubkey text null,
  blockhash numeric null,
  status text null,
  owner_program text null default 'null'::text,
  last_updated timestamp with time zone null default now(),
  rent_lamports text null default 'null'::text,
  constraint sponsored_account_pkey primary key (id)
) TABLESPACE pg_default;