import 'dotenv/config'

const PORT = process.env.PORT;

const KORA_RPC_URL = process.env.KORA_RPC_URL as string;

const HELIUS_DEVNET_RPC= process.env.HELIUS_DEVNET_RPC as string;

const BOT_TOKEN = process.env.BOT_TOKEN as string;

const SOLANA_DEVNET_RPC = process.env.SOLANA_DEVNET_RPC;

const KORA_DEVNET_API = process.env.KORA_DEVNET_API;

const NODE_PUBLIC_SUPABASE_URL = process.env.NODE_PUBLIC_SUPABASE_URL as string;

const NODE_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY = process.env.NODE_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY as string;

const SPONSOR_PUBKEY = process.env.KORA_SPONSOR_PUBLIC_KEY as string;

const KORA_PRIVATE_KEY = process.env.KORA_PRIVATE_KEY as any;

const config = { PORT, KORA_RPC_URL, SPONSOR_PUBKEY,KORA_PRIVATE_KEY ,SOLANA_DEVNET_RPC, HELIUS_DEVNET_RPC, BOT_TOKEN, KORA_DEVNET_API, NODE_PUBLIC_SUPABASE_URL, NODE_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY}

export default config;

